#!/bin/bash

echo "Running prerender"

# Source/load nvm
[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh;

nvm use;

npm run prerender:express &
SERVERPID=$! &
echo $SERVERPID &
npm run prerender:compile;
kill -9 $SERVERPID;